version: "3.5"

x-shared-config:
  base: &base
    command: /bin/bash
    image: opentelemetry/opentelemetry-ruby
    stdin_open: true
    tmpfs:
      - /tmp
    tty: true
    user: "1000:1000"
    volumes:
      - .:/app:cached
      - bundle:/bundle

services:
  api:
    <<: *base
    working_dir: /app/api

  app:
    <<: *base
    build:
      context: .
    working_dir: /app

  # docker-compose run --rm ex-grape bundle install
  # docker-compose run --rm --service-ports ex-grape
  ex-grape:
    <<: *base
    command: bundle exec rackup --host 0.0.0.0 --port 4568 --debug
    environment:
      BUNDLE_GEMFILE: Gemfile
    ports:
      - 4568:4568
    working_dir: /app/examples/http/server/grape

  sdk:
    <<: *base
    working_dir: /app/sdk

volumes:
  bundle:
